### PR TITLE
eightball command

### PR DESCRIPTION
**Pull request by t3h2mas**
For all of those times when you have to take a leap of fate.

Gulp lint was successful.

### CODE REVIEW

**Comment by ltegman** [comment]
I really like the whimsy of this, but I don't think we can move forward with something like this until we can limit features to certain channels as suggested by @SaintPeter. There's some channels that are just too busy already without eightball commands hitting them.

**Comment by ltegman** [comment]
Any chance we could add an :8ball: between the @ mention and the magic 8 ball answer? I think it makes it even more whimsical and makes it more obvious that this is an magic eightball reply.

**Comment by t3h2mas** [comment]
I was looking for an emoticon like that, must have missed it. Added.

**Comment by ltegman** [comment]
Sorry to be so picky, but could you [squash your commits](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one)? I swear after this we'll actually get this merged!

**Comment by ltegman** [comment]
Awesome! :+1:

**Pull request merged**
