### PR TITLE
Fix code formatting wiki link

### PR DESCRIPTION
**Pull request by Manish-Giri**
Replaced the previous wiki link that points to Code Formatting, with the new forum link.

 closes freeCodeCamp/freecodecamp#11372

### CODE REVIEW

**Comment by texas2010** [comment]
@ltegman, this need to deploy soon.  

@Manish-Giri, thank you for change link in the file.

**Comment by Bouncey** [comment]
Closes freeCodeCamp/freeCodeCamp #11372

**Comment by raisedadead** [comment]
Build has been fixed.

**Comment by raisedadead** [comment]
@Manish-Giri do you mind checking this https://github.com/FreeCodeCamp/FreeCodeCamp/issues/11372#issuecomment-257170744 and address this since you are at it?

**Comment by Manish-Giri** [comment]
@raisedadead okay, I'm on it. Thanks for informing!

**Comment by dhcodes** [comment]
This LGTM! Thanks @Manish-Giri

**Pull request merged**
