### PR TITLE
fix regex to ignore username

### LINKED ISSUE #144: bug - ignore brownies when in names
I sent a non thank you message to user iangracia and camperbot gave him brownies. Camperbot should ignore those thank you keywords when they are in a username/ID.

### PR DESCRIPTION
**Pull request by dhcodes**
@raisedadead @systimotic I think this fixes the issue with someone having a 'thanks' keyword in their username. Care to test?

Closes #144

### CODE REVIEW

**Comment by systimotic** [comment]
I'm not late at all! 😅😉 

I'm currently still really low on time and not set up to test camperbot. @raisedadead could you take a look at this?

**Comment by dhcodes** [comment]
@raisedadead could you QA this when you get a second, please :) ?

**Comment by raisedadead** [comment]
@dhcodes thanks a lot for the changes, @BerkeleyTrue can you please deploy when you have a moment.

**Comment by BerkeleyTrue** [comment]
This is now live

**Pull request merged**
