### PR TITLE
add thanks in top 10 FCC languages

### PR DESCRIPTION
**Pull request by dhcodes**
Updated the Regex in RoomMessages.js to accept top 10 languages according to [FCC survey](https://medium.freecodecamp.com/we-asked-15-000-people-who-they-are-and-how-theyre-learning-to-code-4104e29b2781#.f7a8zkchk).

Regex check:
https://regex101.com/r/hH5cN7/47

### CODE REVIEW

**Comment by dhcodes** [comment]
Well I originally thought the tests weren't passing due to something in my Regex, but I can't seem to figure it out.

**Comment by CEREBR4L** [comment]
@dhcodes I don't think the issue is anything to do with your code, mine failed on the same things changing a number from 999 to 1000...

**Comment by atjonathan** [comment]
@dhcodes, yeah! this is a known issue I believe 

cc/ @lgetman

**Comment by dhcodes** [comment]
Thanks for confirming.

**Comment by ltegman** [comment]
Ran the tests after rebasing against my PR that fixes the tests and everything passes 👍  Thanks and sorry for the delay in QA!

**Pull request merged**
