### PR TITLE
Fix/brittle tests

### PR DESCRIPTION
**Pull request by ltegman**
- TextLib test now uses an unchanging copy of the camperbot wiki article.
- Other stylistic changes
- Setup npm test script to run tests without gulp
- Stop using comma separated variable declarations

### CODE REVIEW

**Comment by ltegman** [comment]
Apparently rebasing against the latest master has exposed MORE brittle tests.. looking into it...

**Comment by ltegman** [comment]
@FreeCodeCamp/issue-moderators Could I get someone to lend a review to this when they get the time? Would like to get CI passing again before any more PRs are opened if possible.

**Comment by raisedadead** [comment]
Following, if no one grabs this before this weekend, I'll make some time 😉 ! Looks straight for the last two commits.

Just need to look at the https://github.com/FreeCodeCamp/camperbot/pull/109/commits/68a0616dfc920043c491e234161961d819e991c2 one.

**Comment by raisedadead** [comment]
LGTM. Thanks @ltegman

**Pull request merged**
