### PR TITLE
Fix for the ReDOS vulnerability

### PR DESCRIPTION
**Pull request by snyk-community**
camperbot is currently affected by the high-severity [ReDoS vulnerability](https://snyk.io/vuln/npm:negotiator:20160616). 

Vulnerable module:  `negotiator`
Introduced through:  `express`

This PR fixes the ReDoS vulnerability by upgrading `express` to version 4.14.0. This upgrade will also fix the following other vulnerabilities:
- [Directory Traversal vulnerability](https://snyk.io/vuln/npm:send:20140912) in the `send` dependency.
- [Denial of Service (Event Loop Blocking) vulnerability](https://snyk.io/vuln/npm:qs:20140806-1) in the `qs` dependency.
- [Denial of Service (Memory Exhaustion) vulnerability](https://snyk.io/vuln/npm:qs:20140806) in the `qs` dependency.
- [Cross-Site Scripting vulnerability](https://snyk.io/vuln/npm:express:20140912) in the `express` dependency.
- [Non-Constant Time String Comparison vulnerability](https://snyk.io/vuln/npm:cookie-signature:20160804) in the `cookie-signature` dependency.
- [Root Path Disclosure vulnerability](https://snyk.io/vuln/npm:send:20151103) in the `send` dependency.

Check out the [Snyk test report](https://snyk.io/test/github/FreeCodeCamp/camperbot) to review other vulnerabilities that affect this repo. 

[Watch the repo](https://snyk.io/add) to 
- get alerts if newly disclosed vulnerabilities affect this repo in the future. 
- generate pull requests with the fixes you want, or let us do the work: when a newly disclosed vulnerability affects you, we'll submit a fix to you right away. 

Stay secure, 
The Snyk team

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@raisedadead since you now have CamperBot running locally, can you verify that updating the Express version doesn't seem to break any existing functionality?

**Comment by raisedadead** [comment]
Before I test and merge this, I want to confirm with @BerkeleyTrue

**Comment by BerkeleyTrue** [comment]
@raisedadead Confirm what?

**Comment by raisedadead** [comment]
Opps, sorry incorrect mention. I meant @dhcodes !

Dylan, could also double check?

**Comment by dhcodes** [comment]
Doesn't seem to break anything on my end. Merging in.

**Comment by dhcodes** [comment]
Submitted a revert request. This does actually break the install. Based on the error, Express now has you install middlewares separately so we need to determine which we need to add to `package.json` before we update express. Here's the list: https://github.com/senchalabs/connect#middleware.

**Pull request merged**
