### PR TITLE
simplify making a custom bot

### PR DESCRIPTION
**Pull request by t3h2mas**
### JS
Modified `AppSettings.js` as well as `RoomData.js`. Created `config/usercfg.js` with abstracted data from the modified files to make adding a custom bot user easier.
### Readme
Added instructions to clarify AppID instructions as well as added instructions to get a bot set up with the new `config/usercfg.js` system.

### CODE REVIEW

**Comment by ltegman** [comment]
Great work on this! However, I'd prefer if the user settings were stored in a JSON file and that file should not be committed to the repo. Instead we should tell the user in the `README` what filename they should create and provide a small example of what the contents of that file should look like, much like what is done on the main FCC docs for getting the site app running.

**Comment by SaintPeter** [comment]
You could create an `example.config.json` file with placeholders.

**Comment by t3h2mas** [comment]
Sounds good. I stuck with a js config to keep it dynamic so you only have to change one value to get going. I can switch to a top level json file similar to the example dot.env file.

**Comment by ltegman** [comment]
This looks really good. However, I'm running into a problem when I start the bot with this. At https://github.com/t3h2mas/camperbot/blob/bot-user/config/AppConfig.js#L29 it's looking for the bot in `envConfigs` object, which it is no longer stored in for user defined bots. Also, our linting disallows inline comments, so you'll need to remove those in the two places you have them.

**Comment by t3h2mas** [comment]
The bot is added to the envConfigs object at the bottom so the property can be dynamic. The bot looks for an entry with the prop name of the custom bot user that is consistent with the rest of the code.

Will address the linting issues now

**Comment by t3h2mas** [comment]
Both linting and config.json -> config.githubId pushed

**Comment by ltegman** [comment]
Sorry for the long delay on this. I was testing it today and can't get the bot to actually load up my custom config. Have you been able to successfully get this running a custom bot for you?

**Comment by t3h2mas** [comment]
It worked fine for me. I'm at work but I'll test it tonight or tomorrow.

**Comment by BerkeleyTrue** [comment]
What is the status of this PR?

**Comment by ltegman** [comment]
I'm still unable to get this working. The bot will give me the error from the screenshot saying it joined the room, but it won't actually respond to any messages. I've tried starting over and following the directions from scratch multiple times and still no luck.

**Comment by ltegman** [comment]
Hmmm, I'm not sure what the problem was, but I just kept fiddling with it for a couple hours and eventually it worked. If I ever manage to repro I'll put it in the docs or fix it if it's a bug, but it's working for me now. Sorry it took me so long to get this working and approve -- wish I knew what the issue was!

**Comment by BerkeleyTrue** [comment]
@ltegman :+1:

**Pull request merged**
