### PR TITLE
Add gulp, eslint, and port tests to tape

### LINKED ISSUE #3: Add tests
Add testing suite using Tape

### PR DESCRIPTION
**Pull request by ltegman**
+ Gulp currently just runs tests
+ eslint rules added but not in gulp task
+ removed some uneeded tests
+ updated lodash dep

Closes #3 

Can test by ~~setting `SERVER_ENV=test` in your `dot.env` file and~~ running `gulp`. You'll need to npm install first since some deps have been added and changed.

Further updates coming (linting and making gulp file do more than run tests) but I just wanted to get a PR out there with the tests.

### CODE REVIEW

**Comment by ltegman** [comment]
Added `gulp-env` so that a specific config is not required in your `dot.env` file to make sure console log statements are not shown during tests.

**Comment by ltegman** [comment]
In doing my big linting pass I noticed some lint errors I had in my new tests and an issue with the gulpfile. Force pushed a new version.

Also, linting is almost done and it's a big (positive) change, so there's that to look forward once this is merged :smile:

**Comment by BerkeleyTrue** [comment]
Sorry I haven't had a chance to look at this yet. Is this PR ready to merge or are you still adding tests?

**Comment by ltegman** [comment]
Not a problem, I know you're busy. This PR has ports of all previous mocha tests right now and I'm not planning on adding more unless you'd like me to. I know there was some interest from other contributors in increasing our test coverage, so I figure I'll leave that open for other people if they would like to do that.

**Comment by duffn** [comment]
I'd definitely contribute some more tests and other things after this is merged.

**Comment by BerkeleyTrue** [comment]
Sorry for the delay
1__tmux

**Comment by BerkeleyTrue** [comment]
NVM. I'm guessing I need an api key?

**Comment by ltegman** [comment]
Wooo! Thanks for merging this :smile:. I'll have another massive PR up with linting very soon!

**Comment by BerkeleyTrue** [comment]
Awesome

**Pull request merged**
