### PR TITLE
fix running duplicate thanks

### LINKED ISSUE #59: Double "Thank you" ?
# This happened in chat:
---
@rphares wrote:
> tax @darrylpargeter  @darrylpargeter  @darrylpargeter 

@camperbot responded:

> :star: 714 | @darrylpargeter | [http://www.freecodecamp.com/darrylpargeter](http://www.freecodecamp.com/darrylpargeter)
> :star: 714 | @darrylpargeter | [http://www.freecodecamp.com/darrylpargeter](http://www.freecodecamp.com/darrylpargeter)
> :star: 714 | @darrylpargeter | [http://www.freecodecamp.com/darrylpargeter](http://www.freecodecamp.com/darrylpargeter)

---

Bug? I don't know. But yeah, That is an easier way to spam in chat.
Please fix.

### PR DESCRIPTION
**Pull request by ltegman**
Also did a small refactor of some of the variable declarations.
Closes #59

### CODE REVIEW

**Comment by ltegman** [comment]
This isn't actually a broken build, travis just wasn't configured not to run when there isn't a `.travis.yml` file.

**Comment by Nikitaw99** [comment]
Awaiting merge :)

**Comment by Nikitaw99** [comment]
This kinda takes too long...

**Comment by BerkeleyTrue** [comment]
LGTM

**Pull request merged**
