### PR TITLE
Replace :star: with :poop: for brownie messages

### LINKED ISSUE #25: Replace star with brownie or other desert emoji when showing about
https://github.com/FreeCodeCamp/camperbot/blob/master/nap/lib/bot/cmds/thanks.js#L139

### PR DESCRIPTION
**Pull request by BKinahan**
:poop: is the closest thing to a brownie emoji. It looks happy, and it's funny.

Closes #25

### CODE REVIEW

**Comment by SaintPeter** [comment]
LOL

**Comment by Rafase282** [comment]
I support this :+1:

**Comment by abhisekp** [comment]
:-1: I don't support this. 
Looks absurd. It's not about the icon, the text `:poop:` is inappropriate.

**Comment by Demon000** [comment]
LOL. Can't we simply have an inline image rather than an existing emoji?

**Comment by abhisekp** [comment]
@Demon000 no. That was discussed heavily in the camperbot room.

**Comment by BerkeleyTrue** [comment]
Brown points? ha.

We need a brownie, though.

**Pull request closed without merging**
