### PR TITLE
change .com to .org

### LINKED ISSUE #148: change .com -> .org

### PR DESCRIPTION
**Pull request by texas2010**
close #148 

Please review this.

### CODE REVIEW

**Comment by texas2010** [comment]
@dhcodes  :( I did PR this. I am not sure why you make other PR but I already did this?

**Comment by dhcodes** [comment]
It's because I like doing unnecessary work. 😄. Actually, I didn't open the issue before taking it on. Closing mine. Will QA.

**Comment by dhcodes** [comment]
**LGTM** @texas2010

**Comment by texas2010** [comment]
@dhcodes oh ok. alright.  all good. XD

**Pull request merged**
