### PR TITLE
Comment out add article wiki prompt

### PR DESCRIPTION
**Pull request by chrisdziewa**
Closes issue #32

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
@chrisdziewa use `closes issue #32` so that Github automatically closes that issue when this PR is merged.

**Comment by BerkeleyTrue** [comment]
Sorry, to clarify I meant in the body were you wrote `issue #32`, not the title.

**Comment by chrisdziewa** [comment]
Sorry, I misunderstood. Thanks @BerkeleyTrue

**Comment by BerkeleyTrue** [comment]
:+1:

**Pull request merged**
